chore: add reporter

diff --git a/.github/workflows/e2e-next.yml b/.github/workflows/e2e-next.yml
--- a/.github/workflows/e2e-next.yml
+++ b/.github/workflows/e2e-next.yml
@@ -43,8 +43,28 @@ jobs:
           node-version: 'lts/*'
           check-latest: true
       - name: jest
-        run: echo $CHUNKS | jq '.[${{ matrix.chunk }}] | .[] | @text' | xargs npx jest -c test/e2e/jest.config.js
+        run:
+          echo $CHUNKS | jq '.[${{ matrix.chunk }}] | .[] | @text' | xargs npx jest -c test/e2e/jest.config.js
+          --reporters=jest-junit --reporters=default
         env:
           CHUNKS: ${{ needs.setup.outputs['test-chunks'] }}
           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_BOT_AUTH_TOKEN }}
           NETLIFY_SITE_ID: 1d5a5c76-d445-4ae5-b694-b0d3f2e2c395
+
+      - uses: actions/upload-artifact@v2 # upload test results
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: test-results-${{ matrix.chunk }}
+          path: reports/jest-*.xml
+  report:
+    runs-on: ubuntu-latest
+    needs:
+      - test
+    steps:
+      - uses: dorny/test-reporter@v1
+        with:
+          artifact: /test-results-(.*)/
+          name: Jest Tests $1 # Name of the check run which will be created
+          path: 'reports/*.xml' # Path to test results (inside artifact .zip)
+          max-annotations: 50 # Maximum number of annotations to be created
+          reporter: jest-junit # Format of test results
